// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'project-card': string;
  'project-content': string;
  'project-description': string;
  'project-header': string;
  'project-icon': string;
  'project-image': string;
  'project-link': string;
  'project-preview': string;
  'project-title': string;
  projectCard: string;
  projectContent: string;
  projectDescription: string;
  projectHeader: string;
  projectIcon: string;
  projectImage: string;
  projectLink: string;
  projectPreview: string;
  projectTitle: string;
  'tech-icon': string;
  'tech-icon-container': string;
  'tech-stack': string;
  techIcon: string;
  techIconContainer: string;
  techStack: string;
  tooltip: string;
}
declare const cssExports: CssExports;
export default cssExports;
