// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  accent: string;
  animateText: string;
  avatar: string;
  avatarContainer: string;
  avatarGlow: string;
  avatarWrapper: string;
  buttonsContainer: string;
  mainContainer: string;
  profileContent: string;
  profileSection: string;
  projectCard: string;
  projectsGrid: string;
  projectsSection: string;
  projectsTitle: string;
  pulse: string;
  title: string;
  typewriter: string;
  wakaIcon: string;
  wakaLink: string;
}
declare const cssExports: CssExports;
export default cssExports;
