// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  accent: string;
  animateText: string;
  avatar: string;
  'avatar-container': string;
  'avatar-glow': string;
  'avatar-wrapper': string;
  avatarContainer: string;
  avatarGlow: string;
  avatarWrapper: string;
  'main-container': string;
  mainContainer: string;
  'profile-content': string;
  'profile-section': string;
  profileContent: string;
  profileSection: string;
  'project-card': string;
  projectCard: string;
  'projects-grid': string;
  'projects-section': string;
  'projects-title': string;
  projectsGrid: string;
  projectsSection: string;
  projectsTitle: string;
  pulse: string;
  title: string;
  typewriter: string;
  'waka-icon': string;
  'waka-link': string;
  wakaIcon: string;
  wakaLink: string;
}
declare const cssExports: CssExports;
export default cssExports;
