// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  accent: string;
  container: string;
  controls: string;
  dark: string;
  flag: string;
  header: string;
  lang: string;
  light: string;
  title: string;
}
declare const cssExports: CssExports;
export default cssExports;
