// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  open: string;
  'tech-icon': string;
  'tech-icon-container': string;
  'tech-stack': string;
  'tech-tooltip': string;
  techIcon: string;
  techIconContainer: string;
  techStack: string;
  techTooltip: string;
}
declare const cssExports: CssExports;
export default cssExports;
